spring.application.name=Ostad_Java_SpringBoot_3_Module_15_Assignment
spring.datasource.url=jdbc:h2:mem:notesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
